---
title: "Assignment1 – Loading Data into a Data Frame"
author: "Qixing Li"
date: "January 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning=FALSE)
```

##1.Load all the required libraries
```{r}
library(tidyverse)
```

##2.Download the dataset from UCI & take a glimpse of the dataset
```{r}
col_names = c("Class", "CapShape", "CapSurface","CapColor", "Bruises", "Odor", "GillAttachment","GillSpacing", "GillSize", "GillColor", "StalkShape","StalkRoot", "StalkAbove", "StalkBelow", "ColorAbove","ColorBelow", "VeilType", "VeilColor", "RingNumber","RingType", "SporeColor", "Population", "Habitat")

mash_uci <- read.csv(url("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"), header=FALSE,col.names = col_names)
write_csv(mash_uci,"C:/ds607/mash_uci.csv")
glimpse(mash_uci)
summary(mash_uci)
```

##3.Subsetting data 
It's my sense that odor and color could be easy way to detect whether a mushroom poisonous or not. And I am sure further analysis would be taken in the coming assignment.
```{r}
sub_mush <- mash_uci %>% 
  select("Bruises", "Odor","GillSize", "ColorAbove", "SporeColor" , "Class")
write_csv(sub_mush,"C:/ds607/sub_mush.csv")
dim(sub_mush)
```

##4.Replace appropriates
```{r}
sub_mush$Bruises <- fct_recode(sub_mush$Bruises,
                               "bruises" ="t",
                               "no" = "f")

sub_mush$Odor <- fct_recode(sub_mush$Odor,
                            "almond" ="a",
                            "anise" = "l",
                            "creosote" = "c",
                            "fishy" = "y",
                            "musty" = "m",
                            "none" = "n",
                            "pungent" = "p",
                            "spicy" = "s")

sub_mush$GillSize <- fct_recode(sub_mush$GillSize,
                                "board" ="b",
                                "narrow" = "n")

sub_mush$ColorAbove <- fct_recode(sub_mush$ColorAbove,
                                  "brown" ="n",
                                  "buff" = "b","
                                  cinnamon" = "c",
                                  "gray" = "g",
                                  "orange" = "o",
                                  "pink" = "p",
                                  "red" = "e",
                                  "white" = "w",
                                  "yellow" = "y")

sub_mush$SporeColor <- fct_recode(sub_mush$SporeColor,
                                  "black" ="k",
                                  "buff" = "b",
                                  "brown" = "n",
                                  "chocolate" = "h",
                                  "green" = "r",
                                  "orange" = "o",
                                  "purple" = "u",
                                  "white" = "w",
                                  "yellow" = "y")

sub_mush$Class <- fct_recode(sub_mush$Class,
                             "edible" ="e",
                             "poisonous" = "p")
```



